module.exports = {
	"KEY2CN": {
		"part_0_id": "ID",
		"part_1_type": "类型",
		"part_2_country": "国家",
		"part_2_area": "地区",
		"part_2_city": "城市",
		"part_2_local": "二级地域",
		"part_3_url_TITLE_CN": "标题:官网/网址",
		"part_3_cn_url_TITLE_CN": "标题:中文官网/中文网址",
		"part_3_other_url_TITLE_CN": "标题:其他官网/其他网址",
		"part_3_url": "官网",
		"part_3_cn_url": "中文官网",
		"part_3_other_url": "其他网址",
		"part_3_2_name": "名字",
		"part_3_2_name_jp": "日文名",
		"part_3_2_name_en": "英文名",
		"part_3_markdown": "Markdown",
		"part_3_2_cost": "门票价格",
		"part_3_2_traffic_url": "交通位置指南",
		"part_3_2_address_en": "英文地址",
		"part_3_2_address_cn": "中文地址",
		"part_3_2_time_TITLE_CN": "标题:营业时间/开放时间",
		"part_3_2_time": "营业时间/开放时间",
		"part_3_2_floor_url": "楼层指南",
		"part_3_2_shop_url": "店铺指南",
		"part_3_remarks": "其他信息",
		"part_3_2_gps": "经纬度",
		"part_3_2_local": "地理位置和交通-废弃",
		"part_3_2_pluscode": "Plus code",
		"part_3_2_google_url": "谷歌分享地址",
		"part_3_2_google_html": "谷歌分享页面",
		"part_4_last_save_time": "最后更新时间"
	},
	"KEY2ID": {
		"part_0_id": "_A",
		"part_1_type": "_B",
		"part_2_country": "_C",
		"part_2_area": "_D",
		"part_2_city": "_E",
		"part_2_local": "_F",
		"part_3_url_TITLE_CN": "_G",
		"part_3_cn_url_TITLE_CN": "_H",
		"part_3_other_url_TITLE_CN": "_I",
		"part_3_url": "_J",
		"part_3_cn_url": "_K",
		"part_3_other_url": "_L",
		"part_3_2_name": "_M",
		"part_3_2_name_jp": "_N",
		"part_3_2_name_en": "_O",
		"part_3_markdown": "_P",
		"part_3_2_cost": "_Q",
		"part_3_2_traffic_url": "_R",
		"part_3_2_address_en": "_S",
		"part_3_2_address_cn": "_T",
		"part_3_2_time_TITLE_CN": "_U",
		"part_3_2_time": "_V",
		"part_3_2_floor_url": "_W",
		"part_3_2_shop_url": "_Y",
		"part_3_remarks": "_Z",
		"part_3_2_gps": "_AA",
		"part_3_2_local": "_AB",
		"part_3_2_pluscode": "_AC",
		"part_3_2_google_url": "_AD",
		"part_3_2_google_html": "_AE",
		"part_4_last_save_time": "_AF"
	},
	"ID2KEY": {
		"_A": "part_0_id",
		"_B": "part_1_type",
		"_C": "part_2_country",
		"_D": "part_2_area",
		"_E": "part_2_city",
		"_F": "part_2_local",
		"_G": "part_3_url_TITLE_CN",
		"_H": "part_3_cn_url_TITLE_CN",
		"_I": "part_3_other_url_TITLE_CN",
		"_J": "part_3_url",
		"_K": "part_3_cn_url",
		"_L": "part_3_other_url",
		"_M": "part_3_2_name",
		"_N": "part_3_2_name_jp",
		"_O": "part_3_2_name_en",
		"_P": "part_3_markdown",
		"_Q": "part_3_2_cost",
		"_R": "part_3_2_traffic_url",
		"_S": "part_3_2_address_en",
		"_T": "part_3_2_address_cn",
		"_U": "part_3_2_time_TITLE_CN",
		"_V": "part_3_2_time",
		"_W": "part_3_2_floor_url",
		"_Y": "part_3_2_shop_url",
		"_Z": "part_3_remarks",
		"_AA": "part_3_2_gps",
		"_AB": "part_3_2_local",
		"_AC": "part_3_2_pluscode",
		"_AD": "part_3_2_google_url",
		"_AE": "part_3_2_google_html",
		"_AF": "part_4_last_save_time"
	},
	"VALUE2ID": {
		"PLAY": "P",
		"DIET": "D",
		"SHOP": "S",
		"HOTEL": "H",
		"STRATEGY": "ST",
		"WEBSITE": "W",
		"TRAFFIC":"T",
		"INFORMATION":"I"
	},
	"ID2VALUE": {
		"P": "PLAY",
		"D": "DIET",
		"S": "SHOP",
		"H": "HOTEL",
		"ST": "STRATEGY",
		"W": "WEBSITE",
		"T":"TRAFFIC",
		"I":"INFORMATION"
	},
	"VALUE2CN": {
		"PLAY": "景点游乐园",
		"DIET": "餐饮",
		"SHOP": "购物",
		"HOTEL": "酒店",
		"STRATEGY": "攻略",
		"WEBSITE": "官网",
		"TRAFFIC":"交通枢纽",
		"INFORMATION":"信息中心"
	}
};